// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY7UgP133vR5D6KVg2k1zALUdezskyr48',
    appId: '1:783192734543:android:03ace4f2228bff44afa33a',
    messagingSenderId: '783192734543',
    projectId: 'canguru-6bca1',
    storageBucket: 'canguru-6bca1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBANXCPzTuILHsd0KVWT7t73bwvgYzbEkk',
    appId: '1:783192734543:ios:e37f0270a7045f69afa33a',
    messagingSenderId: '783192734543',
    projectId: 'canguru-6bca1',
    storageBucket: 'canguru-6bca1.appspot.com',
    androidClientId: '783192734543-2lv7pt302dj339gb8rar7i9ini1ao0bm.apps.googleusercontent.com',
    iosClientId: '783192734543-3gmndsss8papt3vheam4kl0q7i4328cv.apps.googleusercontent.com',
    iosBundleId: 'com.inora.cangurugestor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBANXCPzTuILHsd0KVWT7t73bwvgYzbEkk',
    appId: '1:783192734543:ios:e37f0270a7045f69afa33a',
    messagingSenderId: '783192734543',
    projectId: 'canguru-6bca1',
    storageBucket: 'canguru-6bca1.appspot.com',
    androidClientId: '783192734543-2lv7pt302dj339gb8rar7i9ini1ao0bm.apps.googleusercontent.com',
    iosClientId: '783192734543-3gmndsss8papt3vheam4kl0q7i4328cv.apps.googleusercontent.com',
    iosBundleId: 'com.inora.cangurugestor',
  );
}
